// Every row's id is a uuid v7, generated by the backend or by `lib/local/outbox/envelope.ts`, so a
// path segment that is not a uuid cannot name one and needs no request to be refused.
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isEntityId(value: string | undefined): boolean {
  return value !== undefined && UUID.test(value);
}
