import {
  Apple,
  ArrowLeftRight,
  Baby,
  Banknote,
  Bath,
  Battery,
  Bed,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Calculator,
  Camera,
  Car,
  Carrot,
  Cat,
  Church,
  CirclePlus,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Croissant,
  Crown,
  Dog,
  Droplets,
  Dumbbell,
  Film,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  GraduationCap,
  Hammer,
  HandCoins,
  Hash,
  Headphones,
  Heart,
  House,
  IceCreamCone,
  Key,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  type LucideIcon,
  Martini,
  Medal,
  Mountain,
  Music,
  Package,
  Paintbrush,
  PaintBucket,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Radio,
  Receipt,
  Repeat,
  Sandwich,
  Scale,
  Scissors,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Sofa,
  Speaker,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Tag,
  Target,
  Tent,
  Ticket,
  TrainFront,
  Trees,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  WashingMachine,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export const CATEGORY_ICONS = {
  house: House,
  utensils: Utensils,
  car: Car,
  zap: Zap,
  "shopping-bag": ShoppingBag,
  briefcase: Briefcase,
  coins: Coins,
  "circle-plus": CirclePlus,
  repeat: Repeat,
  "credit-card": CreditCard,
  coffee: Coffee,
  stethoscope: Stethoscope,
  dog: Dog,
  cat: Cat,
  pizza: Pizza,
  "shopping-cart": ShoppingCart,
  bus: Bus,
  fuel: Fuel,
  plane: Plane,
  "train-front": TrainFront,
  bike: Bike,
  pill: Pill,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "gamepad-2": Gamepad2,
  music: Music,
  film: Film,
  tv: Tv,
  wifi: Wifi,
  phone: Phone,
  droplets: Droplets,
  flame: Flame,
  lightbulb: Lightbulb,
  shirt: Shirt,
  scissors: Scissors,
  baby: Baby,
  wrench: Wrench,
  hammer: Hammer,
  "paint-bucket": PaintBucket,
  sofa: Sofa,
  bed: Bed,
  key: Key,
  shield: Shield,
  umbrella: Umbrella,
  "hand-coins": HandCoins,
  percent: Percent,
  gift: Gift,
  heart: Heart,
  star: Star,
  trophy: Trophy,
  sprout: Sprout,
  leaf: Leaf,
  beer: Beer,
  wine: Wine,
  cake: Cake,
  "ice-cream-cone": IceCreamCone,
  apple: Apple,
  carrot: Carrot,
  croissant: Croissant,
  sandwich: Sandwich,
  ticket: Ticket,
  popcorn: Popcorn,
  headphones: Headphones,
  camera: Camera,
  laptop: Laptop,
  bath: Bath,
  "washing-machine": WashingMachine,
  trees: Trees,
  mountain: Mountain,
  tent: Tent,
  ship: Ship,
  glasses: Glasses,
  watch: Watch,
  gem: Gem,
  crown: Crown,
  medal: Medal,
  paintbrush: Paintbrush,
  footprints: Footprints,
  cookie: Cookie,
  martini: Martini,
  church: Church,
  store: Store,
  "shopping-basket": ShoppingBasket,
  package: Package,
  truck: Truck,
  plug: Plug,
  battery: Battery,
  radio: Radio,
  speaker: Speaker,
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  banknote: Banknote,
  wallet: Wallet,
  receipt: Receipt,
  calculator: Calculator,
  scale: Scale,
  target: Target,
  layers: Layers,
  "building-2": Building2,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "arrow-left-right": ArrowLeftRight,
  tag: Tag,
  hash: Hash,
} satisfies Record<string, LucideIcon>;

export type CategoryIconKey = keyof typeof CATEGORY_ICONS;

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS) as CategoryIconKey[];

export const FALLBACK_CATEGORY_ICON: CategoryIconKey = "hash";

export function isCategoryIconKey(value: unknown): value is CategoryIconKey {
  return typeof value === "string" && Object.hasOwn(CATEGORY_ICONS, value);
}

export function categoryIcon(key: string | null | undefined): LucideIcon {
  return isCategoryIconKey(key) ? CATEGORY_ICONS[key] : CATEGORY_ICONS[FALLBACK_CATEGORY_ICON];
}
